### ISSUE TITLE
Build paper sooner to cache tectonic downloads

### ISSUE THREAD

**Issue by kburns** [rodluger/corTeX#4]
It looks like cortex is currently caching the conda installation and the tectonic cache folder, but according to [`the docs`](https://docs.travis-ci.com/user/caching/), travis uploads the cache after `script` but before `after_success`.  This means the cache misses all the tex files that cortex pulls down, and will have to re-download them on every build (and this is dominating the building cost for longer papers for me).

It seems like we could get around this by just moving the paper build to the `script` section -- but I'm not sure if there's any reason not to do this?

**Comment by rodluger** [comment]
Thanks for looking into this! There's no reason at all not to do this -- can you issue a PR?

**Comment by kburns** [comment]
Addressed in PR #7
